name: Go test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Install
      run: go install -v ./...

    - name: Show version
      run: cavalry -v

    - name: Run cavalry on docker
      run: cavalry -c example -e docker

    - name: Run cavalry on podman
      run: cavalry -c example -e podman
